#!/system/bin/sh

if [ "a$2" != "a" ];then
  cpu_boost=$2
fi

mount -o remount,rw /

case "${cpu_boost}" in
  on)
    echo "800000" > /sys/module/cpu_boost/parameters/input_boost_freq
    echo "800000" > /sys/module/cpu_boost/parameters/sync_threshold
    echo "500" > /sys/module/cpu_boost/parameters/input_boost_ms
    echo "500" > /sys/module/cpu_boost/parameters/boost_ms
    ;;
  off)
    echo "0" > /sys/module/cpu_boost/parameters/input_boost_freq
    echo "0" > /sys/module/cpu_boost/parameters/sync_threshold
    echo "0" > /sys/module/cpu_boost/parameters/input_boost_ms
    echo "0" > /sys/module/cpu_boost/parameters/boost_ms
    ;;
esac;

mount -o remount,ro /

echo $cpu_boost
