#!/system/bin/sh

if [ "a$2" != "a" ];then
  fade=$2
fi

mount -o remount,rw /

case "${fade}" in
  off)
    echo "0" > /sys/devices/virtual/misc/notification/led_fadein
    echo "0" > /sys/devices/virtual/misc/notification/led_fadeout
    ;;
  on)
    echo "1" > /sys/devices/virtual/misc/notification/led_fadein
    echo "1" > /sys/devices/virtual/misc/notification/led_fadeout
    ;;
esac;

mount -o remount,ro /

echo $fade
