#!/system/bin/sh

if [ "a$2" != "a" ];then
  sharpness=$2
fi

mount -o remount,rw /

case "${sharpness}" in
  off)
    echo "0" > /sys/class/mdnie/mdnie/scenario
    ;;
  on)
    echo "4" > /sys/class/mdnie/mdnie/scenario
    ;;
esac;

mount -o remount,ro /

echo $sharpness
